name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Release Info
        run: |
          {
          echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}"
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}"
          } >> "$GITHUB_ENV"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src

      - name: Install zip
        run: sudo apt-get install zip

      - name: Create zip file
        run: zip -r extension.zip extension

      - name: Upload release asset for Chrome
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./extension.zip
          asset_name: "chrome-${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_TAG }}.zip"
          asset_content_type: application/zip

      - name: Upload release asset for Brave
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./extension.zip
          asset_name: "brave-${{ env.REPOSITORY_NAME }}_${{ env.RELEASE_TAG }}.zip"
          asset_content_type: application/zip
